# US Population Data

## Load data

In [6]:
import pandas as pd

# ŸÇÿ±ÿßÿ°ÿ© ÿßŸÑŸÖŸÑŸÅ
df = pd.read_csv(r"C:\Users\shahe\OneDrive\Desktop\airquality\datasets\us-population-2010-2019.csv")

# ÿπÿ±ÿ∂ ÿ£ÿ≥ŸÖÿßÿ° ÿßŸÑÿ£ÿπŸÖÿØÿ©
print("üìå ÿ£ÿ≥ŸÖÿßÿ° ÿßŸÑÿ£ÿπŸÖÿØÿ©:")
print(df.columns)

# ÿπÿ±ÿ∂ ÿ£ŸàŸÑ 5 ÿµŸÅŸàŸÅ
print("\nüìä ÿ£ŸàŸÑ 5 ÿµŸÅŸàŸÅ ŸÖŸÜ ÿßŸÑÿ®ŸäÿßŸÜÿßÿ™:")
print(df.head())

üìå ÿ£ÿ≥ŸÖÿßÿ° ÿßŸÑÿ£ÿπŸÖÿØÿ©:
Index(['states', 'states_code', 'id', 'year', 'population'], dtype='object')

üìä ÿ£ŸàŸÑ 5 ÿµŸÅŸàŸÅ ŸÖŸÜ ÿßŸÑÿ®ŸäÿßŸÜÿßÿ™:
       states states_code  id  year  population
0     Alabama          AL   1  2010     4785437
1      Alaska          AK   2  2010      713910
2     Arizona          AZ   4  2010     6407172
3    Arkansas          AR   5  2010     2921964
4  California          CA   6  2010    37319502

In [2]:
df.columns

Index(['states', 'states_code', 'id', 'year', 'population'], dtype='object')

In [3]:
new_columns = ['states', 'states_code', 'id', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019']
df = df.reindex(columns=new_columns)
df

,states,states_code,id,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Alabama,AL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,AK,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,AZ,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arkansas,AR,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,California,CA,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Texas,TX,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Florida,FL,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,New York,NY,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Pennsylvania,PA,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Illinois,IL,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Ohio,OH,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Georgia,GA,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,North Carolina,NC,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Michigan,MI,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,New Jersey,NJ,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Virginia,VA,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Washington,WA,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Arizona,AZ,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Massachusetts,MA,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Tennessee,TN,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Indiana,IN,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Missouri,MO,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Maryland,MD,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Wisconsin,WI,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Colorado,CO,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Minnesota,MN,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,South Carolina,SC,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Alabama,AL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Louisiana,LA,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Kentucky,KY,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Oregon,OR,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Oklahoma,OK,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Connecticut,CT,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Utah,UT,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Puerto Rico,PR,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Iowa,IA,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Nevada,NV,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Arkansas,AR,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Mississippi,MS,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Kansas,KS,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,New Mexico,NM,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,North Dakota,ND,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Save data to CSV
df.to_csv('us-population-2010-2019-states-code.csv', index=False)

## Data pre-processing

In [7]:
# Reshape the DataFrame
df_reshaped = pd.melt(df, id_vars=['states', 'states_code', 'id'], var_name='year', value_name='population')

# Convert 'year' column values to integers
df_reshaped['states'] = df_reshaped['states'].astype(str)
df_reshaped['year'] = df_reshaped['year'].astype(int)
df_reshaped['population'] = df_reshaped['population'].str.replace(',', '').astype(int)

df_reshaped

ValueError: value_name (population) cannot match an element in the DataFrame columns.

In [ ]:
# Save reshaped data to CSV
df_reshaped.to_csv('us-population-2010-2019-reshaped.csv')

In [ ]:
# Subset dataframe by year
selected_year = 2019
df_selected_year = df_reshaped[df_reshaped.year == selected_year]
df_selected_year

                   states  states_code  id  year  population
468               Alabama          NaN   1  2019     4903185
469                Alaska          NaN   2  2019      731545
470               Arizona          NaN   4  2019     7278717
471              Arkansas          NaN   5  2019     3017804
472            California          NaN   6  2019    39512223
473              Colorado          NaN   8  2019     5758736
474           Connecticut          NaN   9  2019     3565287
475              Delaware          NaN  10  2019      973764
476  District of Columbia          NaN  11  2019      705749
477               Florida          NaN  12  2019    21477737
478               Georgia          NaN  13  2019    10617423
479                Hawaii          NaN  15  2019     1415872
480                 Idaho          NaN  16  2019     1787065
481              Illinois          NaN  17  2019    12671821
482               Indiana          NaN  18  2019     6732219
483                  Iowa          NaN  19  2019     3155070
484                Kansas          NaN  20  2019     2913314
485              Kentucky          NaN  21  2019     4467673
486             Louisiana          NaN  22  2019     4648794
487                 Maine          NaN  23  2019     1344212
488              Maryland          NaN  24  2019     6045680
489         Massachusetts          NaN  25  2019     6892503
490              Michigan          NaN  26  2019     9986857
491             Minnesota          NaN  27  2019     5639632
492           Mississippi          NaN  28  2019     2976149
493              Missouri          NaN  29  2019     6137428
494               Montana          NaN  30  2019     1068778
495              Nebraska          NaN  31  2019     1934408
496                Nevada          NaN  32  2019     3080156
497         New Hampshire          NaN  33  2019     1359711
498            New Jersey          NaN  34  2019     8882190
499            New Mexico          NaN  35  2019     2096829
500              New York          NaN  36  2019    19453561
501        North Carolina          NaN  37  2019    10488084
502          North Dakota          NaN  38  2019      762062
503                  Ohio          NaN  39  2019    11689100
504              Oklahoma          NaN  40  2019     3956971
505                Oregon          NaN  41  2019     4217737
506          Pennsylvania          NaN  42  2019    12801989
507          Rhode Island          NaN  44  2019     1059361
508        South Carolina          NaN  45  2019     5148714
509          South Dakota          NaN  46  2019      884659
510             Tennessee          NaN  47  2019     6829174
511                 Texas          NaN  48  2019    28995881
512                  Utah          NaN  49  2019     3205958
513               Vermont          NaN  50  2019      623989
514              Virginia          NaN  51  2019     8535519
515            Washington          NaN  53  2019     7614893
516         West Virginia          NaN  54  2019     1792147
517             Wisconsin          NaN  55  2019     5822434
518               Wyoming          NaN  56  2019      578759
519           Puerto Rico          NaN  72  2019     3193694

In [ ]:
# Sort by year
df_selected_year_sorted = df_selected_year.sort_values(by="population", ascending=False)
df_selected_year_sorted

                   states  states_code  id  year  population
472            California          NaN   6  2019    39512223
511                 Texas          NaN  48  2019    28995881
477               Florida          NaN  12  2019    21477737
500              New York          NaN  36  2019    19453561
506          Pennsylvania          NaN  42  2019    12801989
481              Illinois          NaN  17  2019    12671821
503                  Ohio          NaN  39  2019    11689100
478               Georgia          NaN  13  2019    10617423
501        North Carolina          NaN  37  2019    10488084
490              Michigan          NaN  26  2019     9986857
498            New Jersey          NaN  34  2019     8882190
514              Virginia          NaN  51  2019     8535519
515            Washington          NaN  53  2019     7614893
470               Arizona          NaN   4  2019     7278717
489         Massachusetts          NaN  25  2019     6892503
510             Tennessee          NaN  47  2019     6829174
482               Indiana          NaN  18  2019     6732219
493              Missouri          NaN  29  2019     6137428
488              Maryland          NaN  24  2019     6045680
517             Wisconsin          NaN  55  2019     5822434
473              Colorado          NaN   8  2019     5758736
491             Minnesota          NaN  27  2019     5639632
508        South Carolina          NaN  45  2019     5148714
468               Alabama          NaN   1  2019     4903185
486             Louisiana          NaN  22  2019     4648794
485              Kentucky          NaN  21  2019     4467673
505                Oregon          NaN  41  2019     4217737
504              Oklahoma          NaN  40  2019     3956971
474           Connecticut          NaN   9  2019     3565287
512                  Utah          NaN  49  2019     3205958
519           Puerto Rico          NaN  72  2019     3193694
483                  Iowa          NaN  19  2019     3155070
496                Nevada          NaN  32  2019     3080156
471              Arkansas          NaN   5  2019     3017804
492           Mississippi          NaN  28  2019     2976149
484                Kansas          NaN  20  2019     2913314
499            New Mexico          NaN  35  2019     2096829
495              Nebraska          NaN  31  2019     1934408
516         West Virginia          NaN  54  2019     1792147
480                 Idaho          NaN  16  2019     1787065
479                Hawaii          NaN  15  2019     1415872
497         New Hampshire          NaN  33  2019     1359711
487                 Maine          NaN  23  2019     1344212
494               Montana          NaN  30  2019     1068778
507          Rhode Island          NaN  44  2019     1059361
475              Delaware          NaN  10  2019      973764
509          South Dakota          NaN  46  2019      884659
502          North Dakota          NaN  38  2019      762062
469                Alaska          NaN   2  2019      731545
476  District of Columbia          NaN  11  2019      705749
513               Vermont          NaN  50  2019      623989
518               Wyoming          NaN  56  2019      578759

In [ ]:
# Calculate population difference between selected and previous year
def calculate_population_difference(input_df, input_year):
  selected_year_data = input_df[input_df['year'] == input_year].reset_index()
  previous_year_data = input_df[input_df['year'] == input_year - 1].reset_index()
  selected_year_data['population_difference'] = selected_year_data.population.sub(previous_year_data.population, fill_value=0)
  selected_year_data['population_difference_absolute'] = abs(selected_year_data['population_difference'])
  return pd.concat([selected_year_data.states, selected_year_data.id, selected_year_data.population, selected_year_data.population_difference, selected_year_data.population_difference_absolute], axis=1).sort_values(by="population_difference", ascending=False)

df_population_difference_sorted = calculate_population_difference(df_reshaped, selected_year)
df_population_difference_sorted

,states,id,population,population_difference,population_difference_absolute
43,Texas,48,28995881,367215,367215
9,Florida,12,21477737,233420,233420
2,Arizona,4,7278717,120693,120693
33,North Carolina,37,10488084,106469,106469
10,Georgia,13,10617423,106292,106292
47,Washington,53,7614893,91024,91024
5,Colorado,8,5758736,67449,67449
40,South Carolina,45,5148714,64558,64558
42,Tennessee,47,6829174,57543,57543
28,Nevada,32,3080156,52815,52815
44,Utah,49,3205958,52408,52408
4,California,6,39512223,50635,50635
14,Indiana,18,6732219,36722,36722
12,Idaho,16,1787065,36529,36529
37,Oregon,41,4217737,35851,35851
46,Virginia,51,8535519,34233,34233
23,Minnesota,27,5639632,33383,33383
36,Oklahoma,40,3956971,16736,16736
25,Missouri,29,6137428,15805,15805
0,Alabama,1,4903185,15504,15504
49,Wisconsin,55,5822434,15028,15028
35,Ohio,39,11689100,12759,12759
20,Maryland,24,6045680,9878,9878
21,Massachusetts,25,6892503,9868,9868
27,Nebraska,31,1934408,8794,8794
7,Delaware,10,973764,8285,8285
26,Montana,30,1068778,8113,8113
3,Arkansas,5,3017804,8071,8071
17,Kentucky,21,4467673,6520,6520
15,Iowa,19,3155070,6452,6452
29,New Hampshire,33,1359711,6246,6246
41,South Dakota,46,884659,5961,5961
19,Maine,23,1344212,5155,5155
8,District of Columbia,11,705749,4202,4202
31,New Mexico,35,2096829,4088,4088
34,North Dakota,38,762062,3982,3982
22,Michigan,26,9986857,2785,2785
16,Kansas,20,2913314,1955,1955
50,Wyoming,56,578759,1158,1158
39,Rhode Island,44,1059361,1074,1074
38,Pennsylvania,42,12801989,1067,1067
51,Puerto Rico,72,3193694,340,340
45,Vermont,50,623989,-369,369
1,Alaska,2,731545,-3594,3594
30,New Jersey,34,8882190,-3835,3835
11,Hawaii,15,1415872,-4721,4721
24,Mississippi,28,2976149,-4871,4871
6,Connecticut,9,3565287,-6233,6233
18,Louisiana,22,4648794,-10896,10896
48,West Virginia,54,1792147,-12144,12144
13,Illinois,17,12671821,-51250,51250
32,New York,36,19453561,-76790,76790

In [ ]:
# Filter states with population difference > 50000
df_greater_50000 = df_population_difference_sorted[df_population_difference_sorted.population_difference_absolute > 50000]
df_greater_50000

,states,id,population,population_difference,population_difference_absolute
43,Texas,48,28995881,367215,367215
9,Florida,12,21477737,233420,233420
2,Arizona,4,7278717,120693,120693
33,North Carolina,37,10488084,106469,106469
10,Georgia,13,10617423,106292,106292
47,Washington,53,7614893,91024,91024
5,Colorado,8,5758736,67449,67449
40,South Carolina,45,5148714,64558,64558
42,Tennessee,47,6829174,57543,57543
28,Nevada,32,3080156,52815,52815
44,Utah,49,3205958,52408,52408
4,California,6,39512223,50635,50635
13,Illinois,17,12671821,-51250,51250
32,New York,36,19453561,-76790,76790

In [ ]:
# % of States with population difference > 50000
int((len(df_greater_50000)/df_population_difference_sorted.states.nunique())*100)

26

## Plots

### Heatmap

In [ ]:
import subprocess
import sys

try:
    import altair as alt
    print("‚úÖ Altair is already installed!")
except ModuleNotFoundError:
    print("‚ö° Altair not found. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "altair", "vega_datasets"])
    import altair as alt
    print("‚úÖ Altair installed and imported successfully!")

‚ö° Altair not found. Installing...
‚úÖ Altair installed and imported successfully!

In [ ]:
import altair as alt

alt.themes.enable("dark")

heatmap = alt.Chart(df_reshaped).mark_rect().encode(
        y=alt.Y('year:O', axis=alt.Axis(title="Year", titleFontSize=16, titlePadding=15, titleFontWeight=900, labelAngle=0)),
        x=alt.X('states:O', axis=alt.Axis(title="States", titleFontSize=16, titlePadding=15, titleFontWeight=900)),
        color=alt.Color('max(population):Q',
                         legend=alt.Legend(title=" "),
                         scale=alt.Scale(scheme="blueorange")),
        stroke=alt.value('black'),
        strokeWidth=alt.value(0.25),
        #tooltip=[
        #    alt.Tooltip('year:O', title='Year'),
        #    alt.Tooltip('population:Q', title='Population')
        #]
    ).properties(width=900
    #).configure_legend(orient='bottom', titleFontSize=16, labelFontSize=14, titlePadding=0
    #).configure_axisX(labelFontSize=14)
    ).configure_axis(
    labelFontSize=12,
    titleFontSize=12
    )

heatmap

C:\Users\shahe\AppData\Local\Temp\ipykernel_12828\3502662330.py:3: AltairDeprecationWarning:
Deprecated since `altair=5.5.0`. Use altair.theme instead.
Most cases require only the following change:

    # Deprecated
    alt.themes.enable('quartz')

    # Updated
    alt.theme.enable('quartz')

If your code registers a theme, make the following change:

    # Deprecated
    def custom_theme():
        return {'height': 400, 'width': 700}
    alt.themes.register('theme_name', custom_theme)
    alt.themes.enable('theme_name')

    # Updated
    @alt.theme.register('theme_name', enable=True)
    def custom_theme():
        return alt.theme.ThemeConfig(
            {'height': 400, 'width': 700}
        )

See the updated User Guide for further details:
    https://altair-viz.github.io/user_guide/api.html#theme
    https://altair-viz.github.io/user_guide/customization.html#chart-themes
  alt.themes.enable("dark")

alt.Chart(...)

### Choropleth

In [ ]:
# Choropleth via Altair
import altair as alt
from vega_datasets import data

alt.themes.enable("dark")

states = alt.topo_feature(data.us_10m.url, 'states')

alt.Chart(states).mark_geoshape().encode(
    color=alt.Color('population:Q', scale=alt.Scale(scheme='blues')),   # scale=color_scale
    stroke=alt.value('#154360')
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(df_selected_year, 'id', list(df_selected_year.columns))
).properties(
    width=500,
    height=300
).project(
    type='albersUsa'
)

alt.Chart(...)

In [ ]:
import subprocess
import sys

try:
    import plotly.express as px
    print("‚úÖ Plotly is already installed!")
except ModuleNotFoundError:
    print("‚ö° Plotly not found. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "plotly"])
    import plotly.express as px
    print("‚úÖ Plotly installed and imported successfully!")

‚ö° Plotly not found. Installing...
‚úÖ Plotly installed and imported successfully!

In [ ]:
# Choropleth via Plotly
import plotly.express as px

choropleth = px.choropleth(df_selected_year, locations='states_code', color='population', locationmode="USA-states",
                               color_continuous_scale='blues',
                               range_color=(0, max(df_selected_year.population)),
                               scope="usa",
                               labels={'population':'Population'}
                              )
choropleth.update_layout(
        template='plotly_dark',
        plot_bgcolor='rgba(0, 0, 0, 0)',
        paper_bgcolor='rgba(0, 0, 0, 0)',
        margin=dict(l=0, r=0, t=0, b=0),
        height=350
    )

choropleth

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'coloraxis': 'coloraxis',
              'geo': 'geo',
              'hovertemplate': 'states_code=%{location}<br>Population=%{z}<extra></extra>',
              'locationmode': 'USA-states',
              'locations': {'bdata': ('AAAAAAAA+H8AAAAAAAD4fwAAAAAAAP' ... 'AAAAD4fwAAAAAAAPh/AAAAAAAA+H8='),
                            'dtype': 'f8'},
              'name': '',
              'type': 'choropleth',
              'z': {'bdata': ('EdFKAJkpCwB9EG8ATAwuAJ/oWgIQ31' ... 'CtMXQAk1gbAOLXWADH1AgAXrswAA=='),
                    'dtype': 'i4'}}],
    'layout': {'coloraxis': {'cmax': 39512223,
                             'cmin': 0,
                             'colorbar': {'title': {'text': 'Population'}},
                             'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                            'rgb(222,235,247)'], [0.25,
                                            'rgb(198,219,239)'], [0.375,
                                            'rgb(158,202,225)'], [0.5,
                                            'rgb(107,174,214)'], [0.625,
                                            'rgb(66,146,198)'], [0.75,
                                            'rgb(33,113,181)'], [0.875,
                                            'rgb(8,81,156)'], [1.0,
                                            'rgb(8,48,107)']]},
               'geo': {'center': {}, 'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]}, 'scope': 'usa'},
               'height': 350,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 0, 'l': 0, 'r': 0, 't': 0},
               'paper_bgcolor': 'rgba(0, 0, 0, 0)',
               'plot_bgcolor': 'rgba(0, 0, 0, 0)',
               'template': '...'}
})